server:
  port: 8081
  tomcat:
    threads:
      max: 1000

dubbo:
  # 配置服务信息
  application:
    name: order
    # 禁用QOS同一台机器可能会有端口冲突现象
    qos-enable: false
    qos-accept-foreign-ip: false
  # 配置注册中心
  registry:
    address: spring-cloud://localhost
  # 设置协议-协议由提供方指定消费方被动接受
  #protocol:
  #  name: dubbo
   # port: 20880
    # 设置超时时间
  consumer:
    timeout: 4000
    check: false

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    #initialization-mode: always
    #name: order
    url: jdbc:mysql://localhost:3306/order?useUnicode=true&characterEncoding=utf-8&serverTimezone=UTC
    username: root
    password: password
    #schema: classpath:schema.sql
    #data: classpath:testdata.sql
    druid:
      #初始化时建立物理连接的个数
      initial-size: 3
      #最小连接池数量
      min-idle: 3
      #最大连接池数量
      max-active: 100
      #获取连接时最大等待时间
      max-wait: 60000
      filter:
        stat:
          #是否开启慢sql查询监控
          log-slow-sql: true
          #慢SQL执行时间
          slow-sql-millis: 100
      validation-query: select 1
    sql-script-encoding: UTF-8

mybatis:
  #po对象的包
  type-aliases-package: com.example.order.model.po
  #mapper.xml所在的位置
  mapper-locations: classpath*:com.example.order.mapper/*.xml
  #自动将SQL中查出来的带下划线的字段，转换为驼峰标志，再去匹配类中的属性
  configuration:
    #输出产生的SQL
    #log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: true